# Generated by Django 3.2.16 on 2022-12-05 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20221128_0445'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_description',
            field=models.CharField(default='description', max_length=300),
        ),
    ]
