# Generated by Django 3.2.16 on 2022-12-05 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_question_question_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_description',
            new_name='question_description_text',
        ),
    ]
