# Generated by Django 3.2.16 on 2022-12-05 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_alter_question_question_description_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_description_text',
            field=models.CharField(default='description', max_length=300),
        ),
    ]
