# Generated by Django 3.2.16 on 2022-12-05 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_alter_question_question_description_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_short_description_text',
            field=models.CharField(default='short description', max_length=300),
        ),
    ]
