# Generated by Django 3.2.16 on 2022-12-05 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20221205_0550'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdvUser',
        ),
    ]
